# name: spooky-days cd

# on: 
#   push:
#     branches:
#       - main

# jobs:
#   deploy-iac-only:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#             terraform_version: 1.6.6
#             cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
#       - name: Terraform Init
#         run: terraform init
#         working-directory: Terraform

#       - name: Terraform plan
#         run: terraform plan
#         working-directory: Terraform

#       - name: Terraform apply
#         run: terraform apply -auto-approve
#         working-directory: Terraform